import { APP_CONFIG } from "./core/config.js";
import { daysGoneMap } from "./data/games/days-gone/map.js";
import { DAYS_GONE_TRACED_ICON_BODIES } from "./data/games/days-gone/overlay-icons.js";
import { MapEngine } from "./map/MapEngine.js";
import { MapLineLayer } from "./map/MapLineLayer.js";
import { MapMarkerLayer } from "./map/MapMarkerLayer.js";
import { MapLineEditor } from "./ui/MapLineEditor.js";
import { bindControls } from "./ui/Controls.js";

const TYPE_LABELS = { storymissions: "Story missions", encampmentjobs: "Camp jobs", nerosites: "NERO checkpoints", ambushcamps: "Ambush camps", infestations: "Infestation zones", hordes: "Hordes" };
const AUTOSAVE_KEY = "days-gone-speedrun-all-storylines-autosave-v1";
const assetUrl = (path) => new URL(`../${path}`, import.meta.url).href;
const tileTemplateUrl = (template) => assetUrl(template.replace("{x}", "tile-column-placeholder").replace("{y}", "tile-row-placeholder")).replace("tile-column-placeholder", "{x}").replace("tile-row-placeholder", "{y}");
const speedrunMap = { ...daysGoneMap, background: { ...daysGoneMap.background, image: assetUrl(daysGoneMap.background.image) }, tiles: { ...daysGoneMap.tiles, template: tileTemplateUrl(daysGoneMap.tiles.template) } };
const els = Object.fromEntries(["speedrun-status", "speedrun-totals", "speedrun-search", "speedrun-status-filter", "speedrun-filters", "speedrun-list", "objective-title", "objective-details", "objective-x", "objective-y", "route-preview"].map((id) => [id.replaceAll("-", ""), document.querySelector(`#${id}`)]));
const state = { route: [], selected: null, types: new Set(Object.keys(TYPE_LABELS)), region: "", status: "all", missingOnly: false, lines: true, placing: false, endpoint: null, overrides: { routeId: "all-storylines", order: [], coordinates: {}, vectors: {}, transitions: {} } };
function autosave() { localStorage.setItem(AUTOSAVE_KEY, JSON.stringify(state.overrides)); els.speedrunstatus.textContent = "Autosaved locally"; }
function savedDraft() { try { const draft = JSON.parse(localStorage.getItem(AUTOSAVE_KEY) || "null"); return draft?.routeId === "all-storylines" ? draft : null; } catch { return null; } }
let lineEditor;
const engine = new MapEngine({ viewport: document.querySelector("#map-viewport"), canvas: document.querySelector("#map-canvas"), map: speedrunMap, cameraConfig: APP_CONFIG.camera, onMapClick: handleMapPoint, onBackgroundLoad: () => document.querySelector("#map-empty-state").classList.add("is-hidden") });
const markerLayer = new MapMarkerLayer(engine.layers.get("entities"), speedrunMap.size, { renderIcon: routeIcon, onMarkerClick: (marker) => select(marker.id) });
const routeLineLayer = engine.layers.get("routes");
const correctionLayer = new MapLineLayer(engine.layers.get("map-lines"), speedrunMap.size, { onLineClick: (line) => lineEditor?.select(line), onPointPointerDown: (line, index, event) => lineEditor?.movePoint(line, index, event) });
const lineListeners = new Set();
const legId = (stop) => `route-leg-${stop.id}`;
const transition = (stop) => { state.overrides.transitions ??= {}; return state.overrides.transitions[stop.id] ?? {}; };
const missionLegs = () => state.route.slice(1).flatMap((stop, index) => { const previous = state.route[index], before = transition(previous), after = transition(stop); return before.teleport || !previous.position || !stop.position ? [] : [{ id: legId(stop), type: "mission", title: `${previous.label} → ${stop.label}`, points: [before.end ?? previous.position, ...(state.overrides.vectors?.[stop.id] ?? []), after.start ?? stop.position], stopId: stop.id }]; });
const correctionStore = { getAll: missionLegs, subscribe: (listener) => (lineListeners.add(listener), () => lineListeners.delete(listener)), add: () => {}, update: (id, patch) => changeVector(id, patch.points), remove: (id) => changeVector(id, []) };
function changeVector(id, points) { const stop = state.route.find((entry) => legId(entry) === id); if (!stop) return; state.overrides.vectors[stop.id] = (points ?? []).slice(1, -1); autosave(); lineListeners.forEach((listener) => listener(missionLegs())); }
engine.onCameraChange = ({ zoom }) => markerLayer.setZoom(zoom);
bindControls(engine); engine.mount();
lineEditor = new MapLineEditor({ store: correctionStore, layer: correctionLayer, elements: { type: document.createElement("select"), title: document.createElement("input"), start: document.querySelector("#route-line-start"), finish: document.querySelector("#route-line-finish"), cancel: document.querySelector("#route-line-cancel"), delete: document.querySelector("#route-line-delete"), status: document.querySelector("#route-line-status") }, positionForEvent: (event) => engine.coordinates.clamp(engine.coordinates.screenToMap(engine.toViewportPoint(event), engine.camera.getState())), draftForStart: (id) => { const line = missionLegs().find((entry) => entry.id === (id || legId(state.selected))); return line && { ...line, points: line.points.map((point) => ({ ...point })), fixedEndpoints: true }; }, onFinish: (line) => changeVector(line.id, line.points) });
document.querySelector("#map-viewport").addEventListener("click", (event) => { if (state.placing || state.endpoint) handleMapPoint(engine.coordinates.clamp(engine.coordinates.screenToMap(engine.toViewportPoint(event), engine.camera.getState()))); });

function routeIcon(marker) { const color = marker.color || "#f6c453"; const icon = { storymissions: "collectibles", encampmentjobs: "camp", nerosites: "injector", ambushcamps: "ambush", infestations: "infestation", hordes: "horde" }[marker.type]; return `<svg viewBox="0 0 34 34" aria-hidden="true"><circle cx="17" cy="17" r="15" fill="${color}" stroke="#142019" stroke-width="2.5"/><g transform="translate(5 3) scale(.5)" style="color:#142019">${DAYS_GONE_TRACED_ICON_BODIES[icon]}</g><circle cx="25.5" cy="25.5" r="7" fill="#142019" stroke="#f4f1e7" stroke-width="1"/><text x="25.5" y="28" text-anchor="middle" font-family="Arial,sans-serif" font-size="7" font-weight="800" fill="#f4f1e7">${marker.order}</text></svg>`; }
function setCoordinate(position) { if (!state.placing || !state.selected) return false; state.selected.position = { x: Math.round(position.x), y: Math.round(position.y) }; state.overrides.coordinates[state.selected.id] = state.selected.position; state.placing = false; autosave(); render(); return true; }
function setMissionEndpoint(position) { if (!state.endpoint || !state.selected) return false; state.overrides.transitions ??= {}; state.overrides.transitions[state.selected.id] ??= {}; state.overrides.transitions[state.selected.id][state.endpoint] = { x: Math.round(position.x), y: Math.round(position.y) }; state.endpoint = null; autosave(); render(); return true; }
function handleMapPoint(position) { if (!lineEditor?.place(position) && !setMissionEndpoint(position)) setCoordinate(position); }
function regionsFor(completionTitles) { const lookup = new Map(); Object.entries(completionTitles.categories || {}).forEach(([type, category]) => category.titles.forEach((entry) => lookup.set(`${type}:${entry.title}`, entry.region))); return lookup; }
function loadRoute(data) { const regions = regionsFor(data.completionTitles); state.savedOverrides = { routeId: "all-storylines", order: [], coordinates: {}, vectors: {}, ...data.overrides }; state.overrides = { ...state.savedOverrides, ...savedDraft() }; delete state.overrides.lines; state.overrides.vectors ??= {}; const valid = new Set(data.defaultSplits.splits.map((split) => split.id)); state.overrides.order = state.overrides.order.filter((id) => valid.has(id)); const rank = new Map(state.overrides.order.map((id, index) => [id, index])); state.route = data.defaultSplits.splits.map((split, index) => { const goals = [...split.ocrGoals.filter((goal) => data.counters[goal.counterKey]), ...Object.entries(split.auto || {}).flatMap(([counterKey, count]) => Array.from({ length: count }, (_, autoIndex) => ({ id: `auto-${counterKey}-${autoIndex}`, counterKey, label: TYPE_LABELS[counterKey], auto: true })) )]; const types = [...new Set(goals.map((goal) => goal.counterKey))]; const type = split.ocrGoals.find((goal) => data.counters[goal.counterKey])?.counterKey || types[0] || "storymissions"; return { ...split, goals, types, type, region: goals.map((goal) => regions.get(`${goal.counterKey}:${goal.label}`)).find(Boolean) || split.phaseId, position: state.overrides.coordinates[split.id], defaultIndex: index }; }).sort((a, b) => (rank.get(a.id) ?? a.defaultIndex) - (rank.get(b.id) ?? b.defaultIndex)); state.overrides.order = state.route.map((split) => split.id); if (state.route.length !== 240) throw new Error(`Expected 240 route stops; loaded ${state.route.length}.`); const totals = Object.fromEntries(Object.keys(data.counters).map((key) => [key, state.route.reduce((sum, stop) => sum + stop.goals.filter((goal) => goal.counterKey === key).length, 0)])); Object.entries(data.counters).forEach(([key, counter]) => { if (totals[key] !== counter.max) throw new Error(`${counter.label}: expected ${counter.max}, got ${totals[key]}.`); }); state.counters = data.counters; lineListeners.forEach((listener) => listener(missionLegs())); els.speedrunstatus.textContent = "240 route stops loaded"; renderFilters(); render(); }
function filtered() { const search = els.speedrunsearch.value.trim().toLowerCase(); const current = state.route.indexOf(state.selected); return state.route.filter((stop, index) => state.types.has(stop.type) && (!state.region || stop.region === state.region) && (!state.missingOnly || !stop.position) && (state.status === "all" || state.status === "missing" && !stop.position || state.status === "current" && index === current || state.status === "completed" && current >= 0 && index < current || state.status === "upcoming" && current >= 0 && index > current) && (!search || `${stop.label} ${stop.note} ${stop.region}`.toLowerCase().includes(search))); }
function renderFilters() { const regions = [...new Set(state.route.map((stop) => stop.region))].sort(); els.speedrunfilters.replaceChildren(...Object.entries(state.counters).map(([key, counter]) => { const button = document.createElement("button"); button.type = "button"; button.textContent = TYPE_LABELS[key]; button.style.setProperty("--route-color", counter.accent); button.className = "speedrun-filter is-active"; button.addEventListener("click", () => { state.types.has(key) ? state.types.delete(key) : state.types.add(key); button.classList.toggle("is-active", state.types.has(key)); render(); }); return button; }), Object.assign(document.createElement("select"), { innerHTML: `<option value="">All regions</option>${regions.map((region) => `<option>${region}</option>`).join("")}`, onchange: (event) => { state.region = event.target.value; render(); } })); }
function render() { const visible = filtered(); markerLayer.render(visible.filter((stop) => stop.position).map((stop) => ({ id: stop.id, title: stop.label, type: stop.type, color: state.counters[stop.type].accent, order: state.route.indexOf(stop) + 1, position: stop.position }))); renderLines(); els.speedruntotals.replaceChildren(...Object.entries(state.counters).map(([key, counter]) => Object.assign(document.createElement("span"), { textContent: `${counter.shortLabel}: ${state.route.reduce((sum, stop) => sum + stop.goals.filter((goal) => goal.counterKey === key).length, 0)}/${counter.max}`, style: `--route-color:${counter.accent}` }))); els.speedrunlist.replaceChildren(...visible.map((stop) => listItem(stop))); renderDetails(); els.routepreview.value = JSON.stringify(state.overrides, null, 2); }
function renderLines() { routeLineLayer.replaceChildren(); if (!state.lines) { correctionLayer.element.replaceChildren(); return; } lineEditor?.render(); }
function listItem(stop) { const item = document.createElement("li"); item.draggable = true; item.className = `speedrun-stop${stop.id === state.selected?.id ? " is-selected" : ""}${stop.position ? "" : " is-missing"}`; item.innerHTML = `<b>${state.route.indexOf(stop) + 1}</b><span><strong>${stop.label}</strong><small>${TYPE_LABELS[stop.type]} · ${stop.region}${stop.position ? "" : " · needs map position"}</small></span>`; item.addEventListener("click", () => select(stop.id)); item.addEventListener("dragstart", () => { state.dragId = stop.id; }); item.addEventListener("dragover", (event) => event.preventDefault()); item.addEventListener("drop", () => { const from = state.route.findIndex((entry) => entry.id === state.dragId); const to = state.route.findIndex((entry) => entry.id === stop.id); state.route.splice(to, 0, state.route.splice(from, 1)[0]); state.overrides.order = state.route.map((entry) => entry.id); autosave(); render(); }); return item; }
function select(id) { state.selected = state.route.find((stop) => stop.id === id); render(); if (state.selected.position) focus(state.selected.position); }
function renderDetails() { const stop = state.selected; if (!stop) return; const routeTransition = transition(stop); els.objectivetitle.textContent = `${state.route.indexOf(stop) + 1}. ${stop.label}`; const previous = state.route[state.route.indexOf(stop) - 1]; const next = state.route[state.route.indexOf(stop) + 1]; els.objectivedetails.innerHTML = `<p><b>${TYPE_LABELS[stop.type]}</b> · ${stop.region}</p><p>${stop.note || "No split note."}</p><p><b>OCR:</b> ${stop.goals.map((goal) => goal.label).join(" · ")}</p><p><b>Previous:</b> ${previous?.label || "Start"}<br><b>Next:</b> ${next?.label || "Finish"}</p><p>${stop.goals.length > 1 ? `Completing this advances ${stop.goals.length} counters.` : "Completing this advances one counter."}</p>`; els.objectivex.value = stop.position?.x ?? ""; els.objectivey.value = stop.position?.y ?? ""; document.querySelector("#transition-summary").textContent = `Start: ${routeTransition.start ? `${routeTransition.start.x}, ${routeTransition.start.y}` : "uses objective"} · End: ${routeTransition.end ? `${routeTransition.end.x}, ${routeTransition.end.y}` : "uses objective"}${routeTransition.teleport ? " · teleports to next mission" : ""}`; document.querySelector("#teleport-after").setAttribute("aria-pressed", String(Boolean(routeTransition.teleport))); }
function focus(position) { const { width, height } = engine.getViewportSize(); engine.camera.zoom = Math.max(engine.camera.zoom, 0.5); engine.camera.x = width / 2 - position.x * engine.camera.zoom; engine.camera.y = height / 2 - position.y * engine.camera.zoom; engine.render(); }
function setPositionFromInputs() { if (!state.selected) return; const x = Number(els.objectivex.value), y = Number(els.objectivey.value); if (Number.isFinite(x) && Number.isFinite(y)) { state.selected.position = { x, y }; state.overrides.coordinates[state.selected.id] = state.selected.position; autosave(); } render(); }
els.speedrunsearch.addEventListener("input", render);
els.speedrunstatusfilter.addEventListener("change", (event) => { state.status = event.target.value; render(); });
[els.objectivex, els.objectivey].forEach((input) => input.addEventListener("change", setPositionFromInputs));
document.querySelector("#set-coordinate").addEventListener("click", () => { state.placing = true; els.speedrunstatus.textContent = "Click the map to set this coordinate"; });
document.querySelector("#clear-coordinate").addEventListener("click", () => { if (state.selected) { delete state.overrides.coordinates[state.selected.id]; state.selected.position = undefined; autosave(); } render(); });
document.querySelector("#set-mission-start").addEventListener("click", () => { if (state.selected) { state.endpoint = "start"; els.speedrunstatus.textContent = "Click the map to set this mission's start"; } });
document.querySelector("#set-mission-end").addEventListener("click", () => { if (state.selected) { state.endpoint = "end"; els.speedrunstatus.textContent = "Click the map to set this mission's end"; } });
document.querySelector("#teleport-after").addEventListener("click", () => { if (!state.selected) return; const routeTransition = transition(state.selected); state.overrides.transitions[state.selected.id] = { ...routeTransition, teleport: !routeTransition.teleport }; autosave(); render(); });
document.querySelector("#missing-only").addEventListener("click", (event) => { state.missingOnly = !state.missingOnly; event.currentTarget.setAttribute("aria-pressed", String(state.missingOnly)); render(); });
document.querySelector("#jump-current").addEventListener("click", () => state.selected?.position && focus(state.selected.position));
document.querySelector("#fit-route").addEventListener("click", () => document.querySelector("#reset-view").click());
document.querySelector("#fit-region").addEventListener("click", () => { const positions = state.route.filter((stop) => stop.region === state.selected?.region && stop.position).map((stop) => stop.position); if (positions[0]) focus(positions[0]); });
document.querySelector("#route-lines").addEventListener("click", (event) => { state.lines = !state.lines; event.currentTarget.setAttribute("aria-pressed", String(state.lines)); renderLines(); });
document.querySelector("#reset-route-edits").addEventListener("click", () => {
  localStorage.removeItem(AUTOSAVE_KEY); state.overrides = structuredClone(state.savedOverrides); state.overrides.vectors ??= {}; delete state.overrides.lines;
  const rank = new Map(state.overrides.order.map((id, index) => [id, index]));
  state.route.forEach((stop) => { stop.position = state.overrides.coordinates[stop.id]; });
  state.route.sort((a, b) => (rank.get(a.id) ?? a.defaultIndex) - (rank.get(b.id) ?? b.defaultIndex)); state.overrides.order = state.route.map((stop) => stop.id);
  els.speedrunstatus.textContent = "Unsaved edits reset"; render();
});
document.querySelector("#save-route").addEventListener("click", async () => {
  if (!confirm("Save this preview as the local All Storylines coordinate/order override?")) return;
  const response = await fetch("/api/speedrun-route", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(state.overrides) });
  const result = await response.json(); if (response.ok) { state.savedOverrides = structuredClone(state.overrides); localStorage.removeItem(AUTOSAVE_KEY); }
  els.speedrunstatus.textContent = response.ok ? "Route override saved" : result.error;
});
function dataOrder() { return state.route.slice().sort((a, b) => a.defaultIndex - b.defaultIndex).map((stop) => stop.id); }
fetch("/api/speedrun-route").then((response) => response.ok ? response.json() : Promise.reject(new Error("Restart the local editor, then reopen Speedrun Mode."))).then(loadRoute).catch((error) => { els.speedrunstatus.textContent = error.message; });
